baseURL: https://leon-sharma.netlify.app/
languageCode: en-us
title: Portfolio Website for Leon
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: This is my website highlighting some facts about me
    title: Hi, my name is Leon
  blog: {}
  contact:
    address: 
      - city: Cambridge
        country: UK
        street: Homerton Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lsharma.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 07577 067103
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/leon.sharma.58
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/leon0973/
      - icon: fa-github
        label: GitHub
        url: https://github.com/Leon0973
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/leonsharma/
  image: ''
  name: Your name
  navigation:
    links:
      - name: Home
        url: '#'
      - name: Biography
        url: blogs/Biography
      - name: CV
        url: blogs/CV
      - name: Data Project
        url: blogs/DataProject
        - name: Hobbies
        url: blogs/Hobbies
    menu: Menu
    title: LS
  tiles:
    enable: yes
    showcase:
      - image: biography.jpg
        subtitle: I
        title: Biography
        url: blogs/Biography
      - image: Workspace. jpg.jpg
        subtitle: II
        title: CV
        url: blogs/CV
      - image: data.jpeg
        subtitle: III
        title: Data Project
        url: blogs/DataProject
      - image: chess.jpg
        subtitle: IV
        title: Hobbies
        url: blogs/Hobbies
