baseURL: https://leon-sharma.netlify.app/
languageCode: en-us
title: Portfolio Website for Leon
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
   # subtitle: |-
    #  A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
     # AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Leon Sharma
  blog: {}
  contact:
    address: 
      - city: Cambridge
        country: UK
        street: Homerton Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lsharma.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 07577 067103
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/leon.sharma.58
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/leon0973/
      - icon: fa-github
        label: GitHub
        url: https://github.com/Leon0973
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/leonsharma/
  image: ''
  name: Leon Sharma
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
     # - name: Generic Blog
     #   url: blogs/ipsum
     # - name: Elements
     #   url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: biography.jpg
        #subtitle: Ipsum Dolor Sit Amet
        title: Short Biography
        url: blogs/biography
      - image: Workspace. jpg.jpg
        #subtitle: Feugiat Amet Tempus
        title: My CV
        url: blogs/cv
      - image: data.jpeg
        #subtitle: Lorem Etiam Nullam
        title: Example Work in R
        url: blogs/analysis
      - image: chess.jpg
        #subtitle: Nisl Sed Aliquam
        title: Hobbies
        url: blogs/hobbies
  two:
    buttonText: Get Started
    enable: yes
     #subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
     # \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
    #  condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
    #  pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
     # Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      #amet pharetra et feugiat tempus."
    #title: Massa libero
  #  url: blogs
